import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Image from "next/image";
import Rose from "@/assets/rose_shield.svg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          id="background-container"
          className="h-[100dvh] w-[100dvw] overflow-scroll"
        >
          <Image
            src={Rose}
            alt="background"
            layout="fill"
            objectFit="contain"
            className={"-z-10 absolute"}
            id="rose"
          />
          {children}
        </div>
      </body>
    </html>
  );
}
